config/routes.rb
Rails.application.routes.draw do

      
  Spree::Core::Engine.routes.draw do
    namespace :admin do
      resources :properties do
        collection do
          get  :nested_options, :manage, :node_manage
          post :rebuild
        end
      end
    end
  end
   
end

app/models/spree/property_decorator.rb
Spree::Property.class_eval do

    acts_as_nested_set
    include TheSortableTree::Scopes
    
   
end

app/helpers/render_nested_options_helper.rb
module RenderNestedOptionsHelper
  class Render
    class << self
      attr_accessor :h, :options

      def render_node(h, options)
        @h, @options = h, options

        node = options[:node]

        this_node      = options[:selected] == node
        selected_class = this_node ? ' selected' : nil
        selected       = this_node ? " selected='selected'" : nil

        "
        <option value='#{node[:id]}' class='l_#{ options[:level] }#{selected_class}' #{selected}>#{ node[:name] }</option>
        #{ options[:children] }
        "
      end

    end
  end
end

app/helpers/render_sortable_tree_helper.rb
# DOC:
# We use Helper Methods for tree building,
# because it's faster than View Templates and Partials

# SECURITY note
# Prepare your data on server side for rendering
# or use h.html_escape(node.content)
# for escape potentially dangerous content
module RenderSortableTreeHelper
  module Render 
    class << self
      attr_accessor :h, :options

      def render_node(h, options)
        @h, @options = h, options
        node = options[:node]

        "
          <li data-node-id='#{ node.id }'>
            <div class='item'>
              <i class='handle'></i>
              #{ show_link }
              #{ controls }
            </div>
            #{ children }
          </li>
        "
      end

      def show_link
        node = options[:node]
        ns   = options[:namespace]
        url = h.url_for(:controller => 'admin/properties', :action => :show, :id => node)
       #  url = h.url_for(ns + [node])
        title_field = node[:name]
        #p options
        "<h4>#{ h.link_to(title_field, url) }</h4>"
      end

      def controls
        node = options[:node]

        edit_path = h.url_for(:controller => 'admin/properties', :action => :edit, :id => node)
        destroy_path = h.url_for(:controller => 'admin/properties', :action => :destroy, :id => node)

        "
          <div class='controls'>
            #{ h.link_to '', edit_path, :class => :edit }
            #{ h.link_to '', destroy_path, :class => :delete, :method => :delete, :data => { :confirm => 'Are you sure?' } }
          </div>
        "
      end

      def children
        unless options[:children].blank?
          "<ol class='nested_set'>#{ options[:children] }</ol>"
        end
      end

    end
  end
end

app/helpers/render_tree_helper.rb
# DOC:
# We use Helper Methods for tree building,
# because it's faster than View Templates and Partials

# SECURITY note
# Prepare your data on server side for rendering
# or use h.html_escape(node.content)
# for escape potentially dangerous content
module RenderTreeHelper
  class Render
    class << self
      attr_accessor :h, :options

      def render_node(h, options)
        @h, @options = h, options

        node = options[:node]
        "
          <li>
            <div class='item'>
              #{ show_link }
            </div>
            #{ children }
          </li>
        "
      end

      def show_link
        node = options[:node]
        ns   = options[:namespace]
        url  = h.url_for(ns + [node])
        title_field = node[:name]

        "<h4>#{ h.link_to(title_field, url) }</h4>"
      end

      def children
        unless options[:children].blank?
          "<ol>#{ options[:children] }</ol>"
        end
      end

    end
  end
end

app/helpers/the_sortable_tree_helper.rb
module TheSortableTreeHelper
  # Publicated by MIT
  # Nested Set View Helper

  # Ilya Zykin, zykin-ilya@ya.ru, Russia [Ivanovo, Saint Petersburg] 2009-2014
  # github.com/the-teacher

  # Default renderers
  TREE_RENDERERS = {
    :tree     => RenderTreeHelper,
    :sortable => RenderSortableTreeHelper,
    :expandable => RenderExpandableTreeHelper,
    :nested_options => RenderNestedOptionsHelper
  }

  ###############################################
  # Common Base Methods
  ###############################################

  def define_class_of_elements_of tree
    case
      when tree.is_a?(ActiveRecord::Relation) then tree.name.to_s.underscore.downcase
      when tree.empty?                        then nil
      else tree.first.class.to_s.underscore.downcase
    end
  end

  def build_tree_html context, render_module, options = {}
    render_module::Render::render_node(self, options)
  end

  ###############################################
  # Shortcuts
  ###############################################
  
  def just_tree tree, options = {}
    build_server_tree(tree, { :type => :tree }.merge!(options))
  end

  def sortable_tree tree, options = {}
    build_server_tree(tree, { :type => :sortable }.merge!(options))
  end

  def nested_options tree, options = {}
    build_server_tree(tree, { :type => :nested_options }.merge!(options))
  end

  def expandable_tree tree, options = {}
    build_server_tree(tree, { :type => :expandable }.merge!(options))
  end

  ###############################################
  # Server Side Render Tree Helper
  ###############################################

  def build_server_tree(tree, options= {})
    result = ''
    tree   = Array.wrap tree
    opts   = {
      # node and base node params
      :id    => :id,      # node id field
      :title => :title,   # name of title fileld
      :node  => nil,      # node

      # base options
      :type  => :tree,    # tree type
      :root  => false,    # is it root node?
      :level => 0,        # recursion level
      :namespace => [],   # :admin

      # BOOST! hash
      :boost => {} 
    }.merge!(options)

    # Basic vars
    root = opts[:root]
    node = opts[:node]

    # namespace prepare [Rails require]
    opts[:namespace] = Array.wrap opts[:namespace]

    # Module with **Render** class
    opts[:render_module] = TREE_RENDERERS[opts[:type]] unless opts[:render_module]

    # Define tree class
    opts[:klass] = define_class_of_elements_of(tree) unless opts[:klass]

    # BOOST PATCH (BUILD ONCE)
    # solution of main perfomance problem
    # magick index-hash, which made me happy!

    # Performance comparison
    # Boost OFF: 8000 nodes, 3 levels => (Views: 176281.9ms | ActiveRecord: 189.8ms)
    # Boost  ON: 8000 nodes, 3 levels => (Views: 8987.8ms   | ActiveRecord: 141.6ms)

    if opts[:boost].empty?
      tree.each do |item|
        num = item.parent_id || 0
        opts[:boost][num.to_s] = [] unless opts[:boost][num.to_s]
        opts[:boost][num.to_s].push item
      end
    end

    unless node
      # RENDER ROOTS
      roots = opts[:boost]['0']

      # Boost OFF
      # roots = tree.select{ |node| node.parent_id.blank? }

      # define roots, if it's need
      if roots.nil? && !tree.empty?
        min_parent_id = tree.map(&:parent_id).compact.min
        roots = tree.select{ |elem| elem.parent_id == min_parent_id }
      end

      # children rendering
      if roots
        roots.each do |root|
          _opts  =  opts.merge({ :node => root, :root => true, :level => opts[:level].next, :boost => opts[:boost] })
          result << build_server_tree(tree, _opts)
        end
      end
    else
      # RENDER NODE'S CHILDREN
      children_res = ''
      children = opts[:boost][node.id.to_s]

      # Boost OFF
      # children = tree.select{ |_node| _node.parent_id == node.id } 

      opts.merge!({ :has_children => children.blank? })

      unless children.nil?
        children.each do |elem|
          _opts        =  opts.merge({ :node => elem, :root => false, :level => opts[:level].next, :boost => opts[:boost] })
          children_res << build_server_tree(tree, _opts)
        end
      end

      result << build_tree_html(self, opts[:render_module], opts.merge({ :root => root, :node => node, :children => children_res }))
    end

    raw result
  end
end

app/views/spree/admin/_listing_properties.html.erb
<table class="index sortable" id='listing_properties' >

</table>


<ol class="sortable_tree" >
  <%= build_server_tree @properties, :type=> :sortable, :namespace => 'admin' ,:rebuild_url => rebuild_admin_properties_url %>
</ol>

app/views/spree/admin/properties/_editform.html.erb
<div data-hook="admin_property_form" class="align-center row">
  <div class="alpha eight columns">
    <%= f.field_container :name do %>
      <%= f.label :name, class: 'required' %><br />
      <%= f.text_field :name, :class => 'fullwidth' %>
  
      <%= f.error_message_on :name %>
    <% end %>
  </div>

  <div class="eight columns omega">
    <%= f.field_container :presentation do %>
      <%= f.label :presentation, class: 'required' %><br />
      <%= f.text_field :presentation, :class => 'fullwidth' %>
      <%= f.error_message_on :presentation %>
    <% end %>
  </div>
  
    
  
</div>

app/views/spree/admin/properties/_form.html.erb
<div data-hook="admin_property_form" class="align-center row">
  <div class="alpha eight columns">
    <%= f.field_container :name do %>
      <%= f.label :name, class: 'required' %><br />
      <%= f.text_field :name, :class => 'fullwidth' %>
  
      <%= f.error_message_on :name %>
    <% end %>
  </div>

  <div class="eight columns omega">
    <%= f.field_container :presentation do %>
      <%= f.label :presentation, class: 'required' %><br />
      <%= f.text_field :presentation, :class => 'fullwidth' %>
      <%= f.error_message_on :presentation %>
    <% end %>
  </div>
  
    <div class="eight columns omega">
      <%= f.label 'Choose Parent Property', class: '' %>
      <%=select_tag 'property[parent_id]', nested_options(Spree::Property.all, :selected => Spree::Property.first), class: :nested_options%>
  </div>
  
</div>

app/views/spree/admin/properties/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:property_edit) %>
<% end %>


<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_properties_list), spree.admin_properties_path, :icon => 'arrow-left' %>
  </li>
  <li>
    <%= button_link_to Spree.t(:add_property), spree.admin_properties_path, { icon: 'plus', class: 'add-property-button' } %>
  </li>
<% end %>

<%= form_for [:admin, @property] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'editform', :locals => { :f => f } %>
    <div class="filter-actions actions">
      <%= button Spree.t('actions.update'), 'refresh' %>
      <%= button_link_to Spree.t('actions.cancel'), admin_properties_path, :icon => 'remove' %>
    </div>
  </fieldset>

  <% end %>
  
  <ol class="sortable_tree"  >
    <%= build_server_tree @property, :namespace => 'admin' ,type: :sortable %>
  </ol>

app/views/spree/admin/properties/manage.html.erb
<ol class="sortable_tree">
  <%= build_server_tree @properties, type: :sortable %>
</ol>

app/views/spree/admin/properties/show.html.erb
<% content_for :page_title do %>
  Property Show  
<% end %>


<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_properties_list), spree.admin_properties_path, :icon => 'arrow-left' %>
  </li>
  
<% end %>

<ol class="sortable_tree">
  <%= build_server_tree @property,  :namespace => 'admin' ,type: :sortable %>
</ol>